# Generated by Django 3.2.7 on 2021-09-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fa_type', models.CharField(choices=[('ho', 'Hospital'), ('cl', 'Clinic'), ('la', 'Laboratory')], max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('license_number', models.IntegerField(blank=True, null=True)),
                ('specialty', models.CharField(choices=[('an', 'Anaesthesia'), ('pa', 'Pathology'), ('ps', 'Psychiatry'), ('gp', 'General Practitioner'), ('pe', 'Pediatric'), ('de', 'Dermatologist'), ('ur', 'Urologist'), ('ne', 'Neurologist'), ('op', 'Opthalmologist')], max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('health_facility', models.ManyToManyField(to='twin.HealthFacility')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('policy_no', models.IntegerField(blank=True, null=True, verbose_name='Policy Number')),
                ('in_type', models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], max_length=100, verbose_name='Type')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_consultation', models.CharField(choices=[('fi', 'First Visit'), ('fo', 'Follow-up'), ('su', 'Surgery')], max_length=100)),
                ('result', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='twin.practitioner')),
            ],
        ),
    ]
