# Generated by Django 3.2.7 on 2021-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0002_alter_patient_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Policy Number'),
        ),
    ]
