# Generated by Django 3.2.7 on 2021-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0003_alter_insurance_policy_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Policy Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
