# Generated by Django 3.2.7 on 2021-09-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0004_auto_20210925_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='health_facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='twin.healthfacility'),
            preserve_default=False,
        ),
    ]
